"""Initial migration

Revision ID: 73121bdb7cc3
Revises: f8g0h2i4j6k8
Create Date: 2026-02-01 10:20:29.394862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73121bdb7cc3'
down_revision: Union[str, None] = 'f8g0h2i4j6k8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_preferences', 'dream_job_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('90'))
    op.alter_column('alert_preferences', 'interview_reminder_hours',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('24'))
    op.alter_column('alert_preferences', 'daily_digest',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('alert_preferences', 'enabled_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('alert_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('alerts', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_campaign_jobs_campaign_id', table_name='campaign_jobs')
    op.drop_index('ix_campaign_jobs_job_id', table_name='campaign_jobs')
    op.alter_column('jobs', 'remote_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('jobs', 'timezone_requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint('resume_drafts_user_id_fkey', 'resume_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'resume_drafts', 'users', ['user_id'], ['id'])
    op.alter_column('user_achievements', 'earned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_user_achievement', 'user_achievements', type_='unique')
    op.alter_column('user_streaks', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_streaks', 'longest_streak',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_streaks', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_streaks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_streaks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_streaks', 'total_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_streaks', 'longest_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_streaks', 'current_streak',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint('uq_user_achievement', 'user_achievements', ['user_id', 'achievement_id'])
    op.alter_column('user_achievements', 'earned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'resume_drafts', type_='foreignkey')
    op.create_foreign_key('resume_drafts_user_id_fkey', 'resume_drafts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('jobs', 'timezone_requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('jobs', 'remote_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_campaign_jobs_job_id', 'campaign_jobs', ['job_id'], unique=False)
    op.create_index('ix_campaign_jobs_campaign_id', 'campaign_jobs', ['campaign_id'], unique=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('alert_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alert_preferences', 'enabled_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('alert_preferences', 'daily_digest',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alert_preferences', 'interview_reminder_hours',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('24'))
    op.alter_column('alert_preferences', 'dream_job_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('90'))
    # ### end Alembic commands ###
